# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPropertyAnimation, QRect, QTimer
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QWidget


class ArtExhibition(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 656)
        self.img_list = ["E:\毕设\style_transfer\web_window\static\\res_img\\res2023_03_15_16_08_42.jpg",
                         "E:\毕设\style_transfer\web_window\static\\res_img\\res2023_03_20_18_21_36.jpg",
                         "E:\毕设\style_transfer\web_window\static\\res_img\\res2023_03_24_19_27_30.jpg"]
        self.image_index = 0
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1121, 853))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("background: transparent")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(821, 321))
        self.widget_2.setObjectName("widget_2")
        self.widget_2.setStyleSheet("background: transparent")

        self.slider = QtWidgets.QLabel(self.widget_2)
        self.slider.setGeometry(QtCore.QRect(10, 10, 1091, 401))
        self.slider.setMinimumSize(QtCore.QSize(1091, 401))
        self.slider.setObjectName("label")
        self.slider.setAlignment(Qt.AlignCenter)
        self.slider.setPixmap(QPixmap('E:\毕设\style_transfer\web_window\static\\res_img\\res2023_03_20_18_21_36.jpg'))
        #self.slider.setStyleSheet("background-color: rgb(10, 255, 10)")

        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(10, 170, 1051, 80))
        self.widget_4.setMinimumSize(QtCore.QSize(1091, 80))
        self.widget_4.setObjectName("widget_4")
        self.widget_4.setStyleSheet("background: transparent")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton = QtWidgets.QPushButton('<', self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.previous_image)

        self.temp = QtWidgets.QWidget(self.widget_4)
        self.temp.setMinimumSize(QtCore.QSize(661, 41))
        self.temp.setObjectName("widget_5")
        self.horizontalLayout.addWidget(self.temp)

        self.pushButton_2 = QtWidgets.QPushButton('>', self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.pushButton_2.clicked.connect(self.next_image)

        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(821, 291))
        self.widget_3.setObjectName("widget_3")
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 10)")

        self.introduction = QtWidgets.QLabel(self.widget_3)
        self.introduction.setGeometry(QtCore.QRect(10, 10, 1091, 391))
        self.introduction.setMinimumSize(QtCore.QSize(1091, 391))
        self.introduction.setObjectName("label_2")
        self.verticalLayout.addWidget(self.widget_3)
        self.introduction.setStyleSheet("background-color: rgb(50, 255, 200)")
        self.introduction.setText(
            """
            欢迎来到我们的艺术展！
            我们的图像风格迁移软件，采用了前沿的机器学习技术，让您的照片获得一个全新的艺术风格。
            多种风格选择，丰富的调整选项，让您轻松成为一个真正的艺术家！来试试吧，体验无限创意和惊喜！
            """
        )

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.get_img()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.slider.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "<"))
        self.pushButton_2.setText(_translate("Form", ">"))

    def get_img(self):
        pixmap = QPixmap(self.img_list[self.image_index])
        pixmap = pixmap.scaled(self.slider.width(), self.slider.height())
        self.slider.setPixmap(pixmap)

    def next_image(self):
        self.image_index -= 1
        if self.image_index < 0:
            self.image_index = len(self.img_list) - 1

        start_value = self.slider.geometry().x()
        end_value = start_value + 600


        animation = QPropertyAnimation(self.slider, b"geometry")
        animation.setDuration(500)
        animation.setStartValue(QRect(start_value, 0, 600, 350))
        animation.setEndValue(QRect(end_value, 0, 350, 350))
        animation.finished.connect(self.get_img)
        animation.start()
        self.get_img()


    def previous_image(self):
        self.image_index += 1
        if self.image_index >= len(self.img_list):
            self.image_index = 0

        start_value = self.slider.geometry().x()
        end_value = start_value - 600


        animation = QPropertyAnimation(self.slider, b"geometry")
        animation.setDuration(500)
        animation.setStartValue(QRect(start_value, 0, 600, 350))
        animation.setEndValue(QRect(end_value, 0, 350, 350))
        animation.finished.connect(self.get_img)
        animation.start()
        self.get_img()



